In [1]:
import numpy as np
import pandas as pd


In [6]:
df=pd.read_csv(r'C:\Users\India\Desktop\file.csv',index_col=0)

In [7]:
df

Head_orientation_vertical Head_orientation_horizontal   Mouth_open  \
0                   Head down                      Normal  Mouth close   
1                   Head down                      Normal  Mouth close   
2                      Normal                      Normal  Mouth close   
3                   Head down                      Normal  Mouth close   
4                      Normal                      Normal  Mouth close   
..                        ...                         ...          ...   
483                    Normal                      Normal   Mouth open   
484                    Normal                      Normal   Mouth open   
485                    Normal                      Normal   Mouth open   
486                    Normal                      Normal   Mouth open   
487                    Normal                      Normal   Mouth open   

     Phone_detected  Head_count  Head_angles_v  Head_angles_h  target  
0               0.0           1             80             -2       0  
1               0.0           2             77             -1       1  
2               0.0           2             20            -20       1  
3               0.0           2             84             -1       1  
4               0.0           2             12            -30       1  
..              ...         ...            ...            ...     ...  
483             0.0           1             14             -6       0  
484             0.0           1             21             -7       0  
485             0.0           1              3             -5       0  
486             0.0           1             -4              0       0  
487             0.0           1              8             -6       0  

[488 rows x 8 columns]

In [10]:
df.columns

Index(['Head_orientation_vertical', 'Head_orientation_horizontal',
       'Mouth_open', 'Phone_detected', 'Head_count', 'Head_angles_v',
       'Head_angles_h', 'target'],
      dtype='object')

In [8]:
dfcopy=df.copy()

In [18]:
dfcopy['Head_angles_v'].max()

90

In [19]:
dfcopy[ 'Head_angles_h'].max()

57

In [15]:
df=df.drop(['Head_angles_v','Head_angles_h'],axis=1)

In [16]:
df

Head_orientation_vertical Head_orientation_horizontal   Mouth_open  \
0                   Head down                      Normal  Mouth close   
1                   Head down                      Normal  Mouth close   
2                      Normal                      Normal  Mouth close   
3                   Head down                      Normal  Mouth close   
4                      Normal                      Normal  Mouth close   
..                        ...                         ...          ...   
483                    Normal                      Normal   Mouth open   
484                    Normal                      Normal   Mouth open   
485                    Normal                      Normal   Mouth open   
486                    Normal                      Normal   Mouth open   
487                    Normal                      Normal   Mouth open   

     Phone_detected  Head_count  target  
0               0.0           1       0  
1               0.0           2       1  
2               0.0           2       1  
3               0.0           2       1  
4               0.0           2       1  
..              ...         ...     ...  
483             0.0           1       0  
484             0.0           1       0  
485             0.0           1       0  
486             0.0           1       0  
487             0.0           1       0  

[488 rows x 6 columns]

In [24]:
mouth=pd.get_dummies(df['Mouth_open'])

In [25]:
mouth

Mouth close  Mouth open
0              1           0
1              1           0
2              1           0
3              1           0
4              1           0
..           ...         ...
483            0           1
484            0           1
485            0           1
486            0           1
487            0           1

[488 rows x 2 columns]

In [26]:
copy_without_mapping=df.copy()

Mapping all columns

In [28]:
df['Mouth_open']=df['Mouth_open'].map({'Mouth close':0,'Mouth open':1})

In [29]:
df

Head_orientation_vertical Head_orientation_horizontal  Mouth_open  \
0                   Head down                      Normal           0   
1                   Head down                      Normal           0   
2                      Normal                      Normal           0   
3                   Head down                      Normal           0   
4                      Normal                      Normal           0   
..                        ...                         ...         ...   
483                    Normal                      Normal           1   
484                    Normal                      Normal           1   
485                    Normal                      Normal           1   
486                    Normal                      Normal           1   
487                    Normal                      Normal           1   

     Phone_detected  Head_count  target  
0               0.0           1       0  
1               0.0           2       1  
2               0.0           2       1  
3               0.0           2       1  
4               0.0           2       1  
..              ...         ...     ...  
483             0.0           1       0  
484             0.0           1       0  
485             0.0           1       0  
486             0.0           1       0  
487             0.0           1       0  

[488 rows x 6 columns]

In [31]:
df['Head_orientation_horizontal'].unique()

array(['Normal', 'Head right', 'Head left'], dtype=object)

In [32]:
df['Head_orientation_horizontal']=df['Head_orientation_horizontal'].map({'Normal':0,'Head right':1,'Head left':1})

In [33]:
df['Head_orientation_vertical'].unique()

array(['Head down', 'Normal', 'Head up'], dtype=object)

In [34]:
df['Head_orientation_vertical']=df['Head_orientation_vertical'].map({'Normal':0,'Head down':1,'Head up':1})

In [35]:
df

Head_orientation_vertical  Head_orientation_horizontal  Mouth_open  \
0                            1                            0           0   
1                            1                            0           0   
2                            0                            0           0   
3                            1                            0           0   
4                            0                            0           0   
..                         ...                          ...         ...   
483                          0                            0           1   
484                          0                            0           1   
485                          0                            0           1   
486                          0                            0           1   
487                          0                            0           1   

     Phone_detected  Head_count  target  
0               0.0           1       0  
1               0.0           2       1  
2               0.0           2       1  
3               0.0           2       1  
4               0.0           2       1  
..              ...         ...     ...  
483             0.0           1       0  
484             0.0           1       0  
485             0.0           1       0  
486             0.0           1       0  
487             0.0           1       0  

[488 rows x 6 columns]

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 488 entries, 0 to 487
Data columns (total 6 columns):
Head_orientation_vertical      488 non-null int64
Head_orientation_horizontal    488 non-null int64
Mouth_open                     488 non-null int64
Phone_detected                 488 non-null float64
Head_count                     488 non-null int64
target                         488 non-null int64
dtypes: float64(1), int64(5)
memory usage: 46.7 KB


In [36]:
df.columns


Index(['Head_orientation_vertical', 'Head_orientation_horizontal',
       'Mouth_open', 'Phone_detected', 'Head_count', 'target'],
      dtype='object')

In [37]:
df['target'].value_counts()

0    320
1    168
Name: target, dtype: int64

In [39]:
inputs=df.iloc[:,:-1]

In [88]:
inputs.columns.values

array(['Head_orientation_vertical', 'Head_orientation_horizontal',
       'Mouth_open', 'Phone_detected', 'Head_count'], dtype=object)

standardization

In [40]:
df_without_standard=df.copy()

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
target_scaler=StandardScaler()

StandardScaler

In [43]:
target_scaler.fit(inputs)

StandardScaler()

In [44]:
scaled= target_scaler.transform(inputs)

In [45]:
scaled

array([[ 2.83496685, -0.35273781, -0.53311399, -0.37724607, -0.07485418],
       [ 2.83496685, -0.35273781, -0.53311399, -0.37724607,  1.58554772],
       [-0.35273781, -0.35273781, -0.53311399, -0.37724607,  1.58554772],
       ...,
       [-0.35273781, -0.35273781,  1.87577145, -0.37724607, -0.07485418],
       [-0.35273781, -0.35273781,  1.87577145, -0.37724607, -0.07485418],
       [-0.35273781, -0.35273781,  1.87577145, -0.37724607, -0.07485418]])

trainig and testing

In [46]:
from sklearn.model_selection import train_test_split

In [49]:
target_val=df['target']


In [50]:
target_val

0      0
1      1
2      1
3      1
4      1
      ..
483    0
484    0
485    0
486    0
487    0
Name: target, Length: 488, dtype: int64

In [51]:
type(target_val)

pandas.core.series.Series

In [55]:
x_train,x_test,y_train,y_test=train_test_split(scaled,target_val,train_size=0.8)

In [56]:
x_train.shape

(390, 5)

In [57]:
x_test.shape

(98, 5)

shuffle is set true by defualt

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
from sklearn import metrics

In [60]:
reg=LogisticRegression()

In [61]:
reg.fit(x_train,y_train)

LogisticRegression()

In [62]:
reg.score(x_train,y_train)

0.841025641025641

In [63]:
model_output=reg.predict(x_train)
model_output

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,

In [64]:
y_train

275    0
344    0
271    1
250    0
75     1
      ..
286    0
237    0
24     1
126    0
421    1
Name: target, Length: 390, dtype: int64

no of correct predictions

In [68]:
v1=np.sum((model_output==y_train))

In [69]:
v2=model_output.shape[0]

In [70]:
v1/v2

0.841025641025641

intercept and weights

In [72]:
reg.intercept_

array([-0.68641754])

In [73]:
reg.coef_

array([[0.21134354, 0.33703386, 0.34444681, 1.49962837, 0.98556522]])

In [78]:
features=inputs.columns.values

In [79]:
features

array(['Head_orientation_vertical', 'Head_orientation_horizontal',
       'Mouth_open', 'Phone_detected', 'Head_count'], dtype=object)

In [81]:
summary=pd.DataFrame(columns=['Feature'],data=features)
summary['coeff']=np.transpose(reg.coef_)

In [84]:
summary

Feature     coeff
0    Head_orientation_vertical  0.211344
1  Head_orientation_horizontal  0.337034
2                   Mouth_open  0.344447
3               Phone_detected  1.499628
4                   Head_count  0.985565

Testing

In [86]:
reg.score(x_test,y_test)

0.7857142857142857

In [98]:
y_pred = reg.predict(x_test)
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy_percentage = 100 * accuracy
accuracy_percentage

78.57142857142857

['Head_orientation_vertical', 'Head_orientation_horizontal',
       'Mouth_open', 'Phone_detected', 'Head_count']

In [107]:
test1=reg.predict(np.array([0,0,1,67,1]).reshape(1,-1))

In [108]:
test1

array([1], dtype=int64)

In [109]:
test2=reg.predict(np.array([0,1,0,0,2]).reshape(1,-1))

In [110]:
test2

array([1], dtype=int64)

In [121]:
test1=reg.predict(np.array([1,0,0,40,1]).reshape(1,-1))

In [122]:
test1

array([1], dtype=int64)

In [129]:
test1=reg.predict(np.array([0,0,0,0,1]).reshape(1,-1))

if person is outof frame

In [130]:
test1

array([1], dtype=int64)

In [101]:
tfile=pd.read_csv(r'C:\Users\India\Desktop\_Project_\result.csv',index_col=0)

In [102]:
tfile=tfile.drop(['Head_angles_v','Head_angles_h'],axis=1)

In [103]:
tfile['Mouth_open']=tfile['Mouth_open'].map({'Mouth close':0,'Mouth open':1})
tfile['Head_orientation_horizontal']=tfile['Head_orientation_horizontal'].map({'Normal':0,'Head right':1,'Head left':1})
tfile['Head_orientation_vertical']=tfile['Head_orientation_vertical'].map({'Normal':0,'Head down':1,'Head up':1})


In [104]:
tfile

Head_orientation_vertical  Head_orientation_horizontal  Mouth_open  \
0                            0                            0           1   
1                            0                            0           0   
2                            0                            0           1   
3                            0                            0           0   
4                            0                            0           1   
..                         ...                          ...         ...   
104                          0                            0           1   
105                          1                            0           1   
106                          0                            0           1   
107                          1                            0           1   
108                          1                            0           1   

     Phone_detected  Head_count  
0               0.0           1  
1               0.0           1  
2               0.0           1  
3               0.0           1  
4               0.0           1  
..              ...         ...  
104             0.0           1  
105             0.0           1  
106             0.0           1  
107             0.0           1  
108             0.0           1  

[109 rows x 5 columns]